# Generated by Django 3.2 on 2023-02-20 05:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0006_brand_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brand',
            name='image',
        ),
    ]
